[[pocl_next]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e5b05f4f24fd92f6e3f282c88f21967124aef97"
libc = "glibc"
os = "linux"

    [[pocl_next.download]]
    sha256 = "f91d50244a0627e9c5f1bbbb66e1421cd063fe5b86c45ea6c886427349522d94"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.2+1/pocl_next.v7.2.2.i686-linux-gnu-cxx11.tar.gz"
[[pocl_next]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7fd7e07d12589b0e31080a2a9fdeb9d7251d24d0"
libc = "glibc"
os = "linux"

    [[pocl_next.download]]
    sha256 = "214335d5c6ec1343b05b30b2476b7df8061409e34a6679298552af234cf74a2c"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.2+1/pocl_next.v7.2.2.x86_64-linux-gnu-cxx11.tar.gz"
[[pocl_next]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6255248afe0396ddafdfdc248405fc7b914be997"
libc = "glibc"
os = "linux"

    [[pocl_next.download]]
    sha256 = "de44fe1421799c1fef9060b2fe12c4cfc3bffa1ad75075da91b178fd369e7eae"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.2+1/pocl_next.v7.2.2.aarch64-linux-gnu-cxx11.tar.gz"
[[pocl_next]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6b81a571d40430a13982f493aca6ed0ca521edf"
libc = "glibc"
os = "linux"

    [[pocl_next.download]]
    sha256 = "a970c23714e9c716dbd0cb5227effc61116c4c490d1db8dec87f0bef76f74efc"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.2+1/pocl_next.v7.2.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[pocl_next]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f5174a9f761d6cc63398ade140329f8e3f91a8e"
libc = "glibc"
os = "linux"

    [[pocl_next.download]]
    sha256 = "d52be33b0bc1941f876d73dd75568bb92a4b6de0776a5ed19c35f02fea0058e3"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.2+1/pocl_next.v7.2.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[pocl_next]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "53a3325997314b0a2db2ae8f47d25e3173245c14"
libc = "glibc"
os = "linux"

    [[pocl_next.download]]
    sha256 = "15c71bd15cd3c672c36c7e6974eec9aca5568822f26b62b5a13f8ea9ae3a2d7d"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.2+1/pocl_next.v7.2.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[pocl_next]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "333365fa759799b54c85dd849d7dfeadc9def406"
libc = "glibc"
os = "linux"

    [[pocl_next.download]]
    sha256 = "6700646b895cd0ceee6d62a42439ffd1da3813f1c02c35d1c3abf30ae89ef21c"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.2+1/pocl_next.v7.2.2.riscv64-linux-gnu-cxx11.tar.gz"
[[pocl_next]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6e59ce6cdb29bffb6a4e03cfbdeae0a0be47017"
libc = "musl"
os = "linux"

    [[pocl_next.download]]
    sha256 = "9b96beae060f4004330b7e9eb950226b77806746569ac7b1bba94353a1361239"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.2+1/pocl_next.v7.2.2.x86_64-linux-musl-cxx11.tar.gz"
[[pocl_next]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd74304ad4d009c9824c0d13f447acd95a5aa366"
libc = "musl"
os = "linux"

    [[pocl_next.download]]
    sha256 = "b039493e9edbc790decb1724b74493bd7ad471bca6fa0a66ca550048d1cf27d6"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.2+1/pocl_next.v7.2.2.aarch64-linux-musl-cxx11.tar.gz"
[[pocl_next]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3517dd7c7337321ec8bef91c750882b4f60fe82c"
libc = "musl"
os = "linux"

    [[pocl_next.download]]
    sha256 = "a188364c5ff8cf90ed5627adde2c990d91f69f0bfc056cb1d96edd0538c6a2ff"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.2+1/pocl_next.v7.2.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[pocl_next]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f1af15d262733300f9660ff86bcb4c6d0cea4a9"
libc = "musl"
os = "linux"

    [[pocl_next.download]]
    sha256 = "a9ca13a1ae7755413dc6ed49822f318dc94edfb6af7e4b74b11e7ae116246645"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.2+1/pocl_next.v7.2.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[pocl_next]]
arch = "x86_64"
git-tree-sha1 = "733b81489d4ce45eb5a0a6e969645fd0763b7b80"
os = "macos"

    [[pocl_next.download]]
    sha256 = "8b7caf77f6db2b0aee45b53bf12baca3b21dc39b986b52a28cd26bac318129fb"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.2+1/pocl_next.v7.2.2.x86_64-apple-darwin.tar.gz"
[[pocl_next]]
arch = "aarch64"
git-tree-sha1 = "a300cfc6ab6844238d81a3f84100857ed56b614a"
os = "macos"

    [[pocl_next.download]]
    sha256 = "5fdd93c95cfbf3859800cbcc05385857d186a2ab8a04816ba9546df60d8c4a52"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.2+1/pocl_next.v7.2.2.aarch64-apple-darwin.tar.gz"
[[pocl_next]]
arch = "x86_64"
git-tree-sha1 = "654878f38ce1d727265d8db3b04854d65590016d"
os = "freebsd"

    [[pocl_next.download]]
    sha256 = "ce6e15fb826ca6585454b1a459519b249b303d90d5a7b112379ea321fff5054c"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.2+1/pocl_next.v7.2.2.x86_64-unknown-freebsd.tar.gz"
[[pocl_next]]
arch = "aarch64"
git-tree-sha1 = "d1abe9752b64bca6ef58642112efe947c0d896eb"
os = "freebsd"

    [[pocl_next.download]]
    sha256 = "e31888ded0aff34406c9d03802da4ce8c1690bb909c76236fea4ebf6eead18b3"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.2+1/pocl_next.v7.2.2.aarch64-unknown-freebsd.tar.gz"
[[pocl_next]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ffa1ef4342a0016f833f70433a60d0d1d9e2a398"
os = "windows"

    [[pocl_next.download]]
    sha256 = "0378e1127f68c0cb7f72af5b46e974816c27923e8941b08002f44f6be687bdcb"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.2+1/pocl_next.v7.2.2.x86_64-w64-mingw32-cxx11.tar.gz"
