[[pocl_next]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa50ac1386f1339131b413f54270553e925908a3"
libc = "glibc"
os = "linux"

    [[pocl_next.download]]
    sha256 = "48b60b55d22e1dacd5538dfba1c8ef5e0dfc5f6fbadbac26d98a273f5033d6a5"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.1+2/pocl_next.v7.2.1.i686-linux-gnu-cxx11.tar.gz"
[[pocl_next]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3efe04b33b3a52a827d4e95db0aded0fe262cfa5"
libc = "glibc"
os = "linux"

    [[pocl_next.download]]
    sha256 = "4050baaf0c5f6109d5a235df431f253937fbabc758f85b9e1d13c4c37b8130cb"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.1+2/pocl_next.v7.2.1.x86_64-linux-gnu-cxx11.tar.gz"
[[pocl_next]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "87ecb36bdb6c45d094768d48adb3277704757240"
libc = "glibc"
os = "linux"

    [[pocl_next.download]]
    sha256 = "836141ba257b27913e6a6f80ffa84093d0c79a345a305b47cd1425ad76c7c2e7"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.1+2/pocl_next.v7.2.1.aarch64-linux-gnu-cxx11.tar.gz"
[[pocl_next]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f83e5b6a1bd58a971eecd682bac9e3e969af8faf"
libc = "glibc"
os = "linux"

    [[pocl_next.download]]
    sha256 = "db8f69bd25250a71f835bd3d7b4661eacf8888d0051dfb26a3faf3079b803d14"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.1+2/pocl_next.v7.2.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[pocl_next]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1b84b2b45f236b4b66f97d236d9b4bc40a6b9882"
libc = "glibc"
os = "linux"

    [[pocl_next.download]]
    sha256 = "e4bd3d8c5da4b8969b61d4dafb539e20909e6f236e4bc345b948738d7e65199b"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.1+2/pocl_next.v7.2.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[pocl_next]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed952b6b7f7dc2da97c73aef27152c1c7ee6d331"
libc = "glibc"
os = "linux"

    [[pocl_next.download]]
    sha256 = "c38bebda288f92f78d01371cf3ef4c71e70fbf21dedaf10c2147a78d7412f399"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.1+2/pocl_next.v7.2.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[pocl_next]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b821cf22f9e5fc7d52e718b6aebbd48fa08dafc"
libc = "glibc"
os = "linux"

    [[pocl_next.download]]
    sha256 = "73a86ac034e8025b3d065481eb4b43941568232cad5466985cd4aa1d4088e8fe"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.1+2/pocl_next.v7.2.1.riscv64-linux-gnu-cxx11.tar.gz"
[[pocl_next]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "481c7e65bb9ccc5d0e9f934fd1aa090e9dfe9b1e"
libc = "musl"
os = "linux"

    [[pocl_next.download]]
    sha256 = "ee936f50b69ebda5e3969a43ad01365651a48b905c48d218ddd040c75a280c70"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.1+2/pocl_next.v7.2.1.x86_64-linux-musl-cxx11.tar.gz"
[[pocl_next]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a36de5a3512710fb25ee233c004055cc28b73b49"
libc = "musl"
os = "linux"

    [[pocl_next.download]]
    sha256 = "2f601f6faffb73083c5d092cd94418d4d6b3a5751a6766b831e51c26022e151b"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.1+2/pocl_next.v7.2.1.aarch64-linux-musl-cxx11.tar.gz"
[[pocl_next]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "392fd258631e3f313cd4bd2bfbdd9949d45c880d"
libc = "musl"
os = "linux"

    [[pocl_next.download]]
    sha256 = "be0abe264a7b3b8c10d77545feb60fc6e65538dc7cb2b17dad0565d9015773b5"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.1+2/pocl_next.v7.2.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[pocl_next]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7abc6d4daf274aa862267dce867522b5580b5154"
libc = "musl"
os = "linux"

    [[pocl_next.download]]
    sha256 = "6ca2ded3641fb904c26fc40643fee8da6ce385c772f3dd1f479168c516f40dd6"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.1+2/pocl_next.v7.2.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[pocl_next]]
arch = "x86_64"
git-tree-sha1 = "557bab7bcc48f2e6e5fa649cc75bbf964afbe041"
os = "macos"

    [[pocl_next.download]]
    sha256 = "1c2e8dc472cdfaa3e8d3081f22142a16671e069f6d004de81376f879da40a847"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.1+2/pocl_next.v7.2.1.x86_64-apple-darwin.tar.gz"
[[pocl_next]]
arch = "aarch64"
git-tree-sha1 = "52c5b614a3c5f44ffbf279edaf8901f5ce20991e"
os = "macos"

    [[pocl_next.download]]
    sha256 = "cc32e60ad7ef2d4f945781621d890d639f21b0f22e5cb6456c0e9091c5675adc"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.1+2/pocl_next.v7.2.1.aarch64-apple-darwin.tar.gz"
[[pocl_next]]
arch = "x86_64"
git-tree-sha1 = "a6357c1249e4c79b0e21fc97e0326a65937d5de6"
os = "freebsd"

    [[pocl_next.download]]
    sha256 = "87e9c0d55213fbd9cb3ab12ff456beb5e0334e53d20fe8661f46b36042703331"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.1+2/pocl_next.v7.2.1.x86_64-unknown-freebsd.tar.gz"
[[pocl_next]]
arch = "aarch64"
git-tree-sha1 = "eff6a502d10691e2f2cbebf46e66cd1e5dc515ab"
os = "freebsd"

    [[pocl_next.download]]
    sha256 = "f2d32c77a0528748f2f665f0642d58c6a466266554640c21688df23c3c6987cb"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.1+2/pocl_next.v7.2.1.aarch64-unknown-freebsd.tar.gz"
[[pocl_next]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b70c156d58faef3adb24d924d5639b0391b5182e"
os = "windows"

    [[pocl_next.download]]
    sha256 = "ae3996f6f4f085020cc7ccef19d4a6b3bd01918574dbf0c74f60ff0a50e04c6d"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.1+2/pocl_next.v7.2.1.x86_64-w64-mingw32-cxx11.tar.gz"
