[[pocl_next]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80e659e4fee6e4af9e572195a0cee1f00475bd40"
libc = "glibc"
os = "linux"

    [[pocl_next.download]]
    sha256 = "e9e6be2322d817ee6cf1b232b2714ce7a758edca787600fb998d41a77029e282"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.0+25/pocl_next.v7.2.0.i686-linux-gnu-cxx11.tar.gz"
[[pocl_next]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c8a01cebce091f403ad7f043b151f3734a8cb63"
libc = "glibc"
os = "linux"

    [[pocl_next.download]]
    sha256 = "912cdfac1b6341c6696524d08dd87e15aaf170b2258f6a93e03c7c714f3b4782"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.0+25/pocl_next.v7.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[pocl_next]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b1a1a57f8f1755c51d4638b7a980bf289d719f4"
libc = "glibc"
os = "linux"

    [[pocl_next.download]]
    sha256 = "3f4ffbe96c269a5626a1cf901e1d96ae6ddb79b7fe6645e54a785b8e3a429a26"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.0+25/pocl_next.v7.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[pocl_next]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7399b2d9e76740be03da152314746e490fc7675f"
libc = "glibc"
os = "linux"

    [[pocl_next.download]]
    sha256 = "16249adefc106a6e2427941038d295ce615df4a9642de6a0f7a869ea0cd37961"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.0+25/pocl_next.v7.2.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[pocl_next]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a198a36ed8562622e60ada384b02ca79f76eae8f"
libc = "glibc"
os = "linux"

    [[pocl_next.download]]
    sha256 = "baa18eddb9789e2d9e272255653bbe5ed9c7689c1caed2749a9cb8464cac34fa"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.0+25/pocl_next.v7.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[pocl_next]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3920818ee21ee160773c622c708d976c3294226f"
libc = "glibc"
os = "linux"

    [[pocl_next.download]]
    sha256 = "2bac1cb0f371247d214dbc0f7f9d9396ebc8ea538fab1be02273c8ee545e952f"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.0+25/pocl_next.v7.2.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[pocl_next]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83edf240cee00e5d1d62cac1059f99b857ad87eb"
libc = "glibc"
os = "linux"

    [[pocl_next.download]]
    sha256 = "be53c1c91733b11d0b45a166f75cfb177f41ae3977f1eac2beabcb7029d1ab55"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.0+25/pocl_next.v7.2.0.riscv64-linux-gnu-cxx11.tar.gz"
[[pocl_next]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "84d5c30f0f78131bb5b2ccbec8f5b6fb7a97af5b"
libc = "musl"
os = "linux"

    [[pocl_next.download]]
    sha256 = "938f07f810cd64e254f8e2d2cfe15a6e493fbd4a16904992c2706d4e4ac90c8c"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.0+25/pocl_next.v7.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[pocl_next]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4fa4da392ea0832dbf0354e9abbc60e7a713b6cf"
libc = "musl"
os = "linux"

    [[pocl_next.download]]
    sha256 = "5316d22948d7c17187b9ad9c40ebf145ca89cba7dec8bc73857022fecd9dd58b"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.0+25/pocl_next.v7.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[pocl_next]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e940b89be7c5d7d6e4ef765ff6d7b88bbe56ee7"
libc = "musl"
os = "linux"

    [[pocl_next.download]]
    sha256 = "0e126fbc960c3b12862472272f179eb91e8f38ebed910fdc00d24d241f9183b8"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.0+25/pocl_next.v7.2.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[pocl_next]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1677aafaf047fae4d624417ca428603e8c2a9f5b"
libc = "musl"
os = "linux"

    [[pocl_next.download]]
    sha256 = "e8f9c325a97594041ccc58eae8f77846146367b9455a81f2ed907b9879f7c28d"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.0+25/pocl_next.v7.2.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[pocl_next]]
arch = "x86_64"
git-tree-sha1 = "1ebe639b1ff30da4edeb5ef0bd7807f9f013c5d0"
os = "macos"

    [[pocl_next.download]]
    sha256 = "89953b22e063b9a84a41239a5cdd321529517101071ba2abf449b50dafa96e02"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.0+25/pocl_next.v7.2.0.x86_64-apple-darwin.tar.gz"
[[pocl_next]]
arch = "aarch64"
git-tree-sha1 = "3ac1e099d602e5558079895263ac96fd64af3ac7"
os = "macos"

    [[pocl_next.download]]
    sha256 = "138158d515a3e929a8c0e63d4b5f9ad23a50f9e2dbad71bb9fe5aa1557119b9a"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.0+25/pocl_next.v7.2.0.aarch64-apple-darwin.tar.gz"
[[pocl_next]]
arch = "x86_64"
git-tree-sha1 = "fcccaefa7795a179ad187b85186acea9ee830590"
os = "freebsd"

    [[pocl_next.download]]
    sha256 = "d95d6c97169fa9c9deb937d0bd757b232acee4ace791fece60afcb395fb9a696"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.0+25/pocl_next.v7.2.0.x86_64-unknown-freebsd.tar.gz"
[[pocl_next]]
arch = "aarch64"
git-tree-sha1 = "5bec30c0e954ca3c82ed4760646c6d30fb0cf91d"
os = "freebsd"

    [[pocl_next.download]]
    sha256 = "d896056f7be7def33a130da47ea3d833584e9d1adae81f46668ff1b2adcd3c95"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.0+25/pocl_next.v7.2.0.aarch64-unknown-freebsd.tar.gz"
[[pocl_next]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b8d0bc49cb67e7d196ff2483827c2ed3b44530c3"
os = "windows"

    [[pocl_next.download]]
    sha256 = "c9a7ddb4ff0d580378f558c0112e7563f837263ec79d2f4529148dbb020bd2ce"
    url = "https://github.com/JuliaBinaryWrappers/pocl_next_jll.jl/releases/download/pocl_next-v7.2.0+25/pocl_next.v7.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
