# Autogenerated wrapper script for pocl_next_jll for powerpc64le-linux-gnu-cxx11
export libpocl, poclcc

using OpenCL_jll
using OpenCL_Headers_jll
using Hwloc_jll
using Zstd_jll
JLLWrappers.@generate_wrapper_header("pocl_next")
JLLWrappers.@declare_library_product(libpocl, "libpocl.so.2")
JLLWrappers.@declare_executable_product(poclcc)
function __init__()
    JLLWrappers.@generate_init_header(OpenCL_jll, OpenCL_Headers_jll, Hwloc_jll, Zstd_jll)
    JLLWrappers.@init_library_product(
        libpocl,
        "lib/libpocl.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        poclcc,
        "bin/poclcc",
    )

    JLLWrappers.@generate_init_footer()
    # Register this driver with OpenCL_jll
if OpenCL_jll.is_available()
    push!(OpenCL_jll.drivers, libpocl)
end

end  # __init__()
